name: Popular Psychology
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24702
title: 'Popular Psychology: Exploring the Intersection of Psychology and Daily Life'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#15191c'
    - '#373b46'
    - '#dac9b9'
    - '#9da0a4'
  brandStrength: 0.8125
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
