name: Popular Psychology
favicon: null
layout_spectrum: 0.6742504995781928
typography_spectrum: 0.7204230825882405
title: 'Popular Psychology: Exploring the Intersection of Psychology and Daily Life'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.23563417443074286
  lightness: 0.5389657497871667
  saturation: 0.4358954045455903
  rhythmicContrast: 0.11099073546938598
purpose: []
