name: Popular Psychology
favicon: null
layout_spectrum: 0.50496
typography_spectrum: 0
title: 'Popular Psychology: Exploring the Intersection of Psychology and Daily Life'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2f3920'
    - '#9aaf22'
    - '#b7b7b5'
    - '#b56644'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
